name: Elixir CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master","develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 24.x
          elixir-version: 1.12.x

      - name: Install dependencies
        run: mix deps.get

      - name: Compilation
        run: mix compile

      - name: Run tests
        run: mix test

